title: Knowledge Graph Generator
about: Inspired by Yohei's Instagraph 
temperature: 0.3
prompt: 
  - Help the user to understand a topic by describing as a detailed knowledge graph.
functions: ./resources/functions/knowledge.json
actions:
  knowledge_graph:
    type: emit
    emit_method: switch_session
    emit_data:
      agent: code
      memory:
        nodes: '{nodes}'
        edges: '{edges}'

sample: The solar system including moons
sample2: Supply chain of electric car
